SET SCHEMA 'zafira';

DO $$
DECLARE GROUP_ID GROUPS.id%TYPE;
DECLARE USER_ID USERS.id%TYPE;

BEGIN
	INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('${username}', '${password}') RETURNING id INTO USER_ID;

	SELECT ID FROM GROUPS WHERE NAME = '${group}' INTO GROUP_ID;

	INSERT INTO USER_GROUPS(USER_ID, GROUP_ID) VALUES (USER_ID, GROUP_ID);

	INSERT INTO USER_PREFERENCES (NAME, VALUE, USER_ID) VALUES
		('REFRESH_INTERVAL', '0', USER_ID),
		('DEFAULT_DASHBOARD', 'General', USER_ID),
		('THEME', '32', USER_ID);
END$$;
