DO
$$
    DECLARE
        SUPER_ADMINS_GROUP_ID GROUPS.id%TYPE;
        ADMINS_GROUP_ID       GROUPS.id%TYPE;
        USERS_GROUP_ID        GROUPS.id%TYPE;
        PERMISSION_ID         PERMISSIONS.id%TYPE;

    BEGIN
        SUPER_ADMINS_GROUP_ID := (SELECT ID FROM GROUPS WHERE NAME = 'Super admins');
        ADMINS_GROUP_ID := (SELECT ID FROM GROUPS WHERE NAME = 'Admins');
        USERS_GROUP_ID := (SELECT ID FROM GROUPS WHERE NAME = 'Users');
        INSERT INTO PERMISSIONS (NAME, BLOCK)
        VALUES ('FETCH_INTEGRATIONS', 'INTEGRATIONS')
        RETURNING id INTO PERMISSION_ID;
        INSERT INTO GROUP_PERMISSIONS (GROUP_ID, PERMISSION_ID)
        VALUES (SUPER_ADMINS_GROUP_ID, PERMISSION_ID),
               (ADMINS_GROUP_ID, PERMISSION_ID),
               (USERS_GROUP_ID, PERMISSION_ID);
    END
$$;
