DO $$
    DECLARE
        INTEGRATION_ID INTEGRATIONS.ID%TYPE;
        JOB_ID JOBS.ID%TYPE;
    BEGIN
        SELECT INTEGRATIONS.ID FROM INTEGRATIONS WHERE INTEGRATIONS.NAME = 'JENKINS' INTO INTEGRATION_ID;

        FOR JOB_ID IN SELECT * FROM JOBS
            LOOP
                UPDATE JOBS SET AUTOMATION_SERVER_ID = INTEGRATION_ID WHERE JOBS.ID = JOB_ID;
            END LOOP;
        RETURN;
    END$$;