DO
$$
    DECLARE
        SUPER_ADMINS_GROUP_ID_VAR GROUPS.id%TYPE;
        ADMINS_GROUP_ID_VAR       GROUPS.id%TYPE;
        PERMISSION_ID_VAR         PERMISSIONS.id%TYPE;

    BEGIN

        SUPER_ADMINS_GROUP_ID_VAR := (SELECT ID FROM GROUPS WHERE NAME = 'Super admins');
        ADMINS_GROUP_ID_VAR := (SELECT ID FROM GROUPS WHERE NAME = 'Admins');

        INSERT INTO PERMISSIONS (NAME, BLOCK)
        VALUES ('REFRESH_TOKEN', 'TEST_SESSIONS')
        RETURNING id INTO PERMISSION_ID_VAR;

        INSERT INTO GROUP_PERMISSIONS (GROUP_ID, PERMISSION_ID) VALUES (SUPER_ADMINS_GROUP_ID_VAR, PERMISSION_ID_VAR);
        INSERT INTO GROUP_PERMISSIONS (GROUP_ID, PERMISSION_ID) VALUES (ADMINS_GROUP_ID_VAR, PERMISSION_ID_VAR);

    END
$$;