require('../bower_components/elasticsearch/elasticsearch.angular.min');
require('angular-translate');
require('angular-translate-loader-static-files');
require('angular-material');
require('angular-scroll');
require('../bower_components/jquery.slimscroll/jquery.slimscroll.min');
// require('echarts');
require('../vendors/ngecharts');
require('../bower_components/jquery-ui/jquery-ui.min');
require('lodash');
require('../bower_components/gridstack/dist/gridstack.all');
require('../bower_components/gridstack-angular/dist/gridstack-angular.min');
require('../bower_components/ng-img-crop/compile/minified/ng-img-crop');
require('../bower_components/ace-builds/src-min-noconflict/ace');
require('../bower_components/angular-ui-ace/ui-ace.min');
require('../bower_components/jszip/dist/jszip.min');
// require('../vendors/html2canvas.min');
require('html2canvas');
require('../vendors/md-date-range-picker');
require('../vendors/highlight.pack');
