SELECT cron.schedule ('1 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST_32_DAYS_VIEW$$);
SELECT cron.schedule ('5 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.LAST_93_DAYS_VIEW$$);
SELECT cron.schedule ('10 0 * * *', $$REFRESH MATERIALIZED VIEW CONCURRENTLY zafira.TOTAL_VIEW$$);